name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is being marked as stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
        stale-issue-label: 'stale'
        stale-pr-message: 'This Pull Request is being marked as stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
        stale-pr-label: 'stale'
        days-before-stale: 30
        days-before-close: 5
        exempt-issue-labels: '' # Comma seperated list of labels that should be used to exempt an issue/pr from being marked as stale or being closed
